name: activity-detector
dependencies:
- cycler=0.10.0=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- libgfortran=3.0=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- matplotlib=1.5.1=np111py35_0
- mkl=11.3.1=0
- numpy=1.11.0=py35_0
- openssl=1.0.2g=0
- pip=8.1.1=py35_1
- pyparsing=2.1.1=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.5.2=py35_0
- pytz=2016.3=py35_0
- qt=4.8.7=1
- readline=6.2=2
- scikit-learn=0.17.1=np111py35_0
- scipy=0.17.0=np111py35_2
- setuptools=20.7.0=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - audioread==2.1.2
  - decorator==4.0.9
  - joblib==0.9.4
  - librosa==0.4.2

